Dsacademy books daniela vlasceanu
DataSentics/dsacademy-books pull request #7
Opened 2022-10-11 13:09 UTC by VlsDanielaGb

2022-10-12 07:09 UTC, MarekTejcDS requested changes
Not sure if I missed it, but there should be `something` that will check if there are any running streams (reading or writing) and stop them - otherwise they will be running forever, and we surely don't want it for now.

2022-10-12 07:09 UTC, MarekTejcDS commented on src/daniela-gabriela-vlasceanu/workflow_config.json
> +                    "num_workers": 8
For this task this is mostly overrated value - there can be just one worker

2022-10-12 07:26 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/most-popular-10-books.py
> +    if 646 <= period and period <= 1:
it's 646 because i took the smallest year and the latest and this was the difference.

2022-10-12 07:30 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/workflow_config.json
> +                    "num_workers": 8
it seems like one of the tasks in workflow had another cluster then the one i created. I changed that!

2022-10-12 07:33 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/bronze/books-bronze.py
> +        "/dbfs/user/daniela-gabriela.vlasceanu@datasentics.com/dbacademy/daniela_books_raw_checkpoint/",
I'm using trigger(availableNow=True) when writing the stream afterwards  and i thought that is the way to stop it when it does not have any more data to process. And as for these path's and checkpoints i will change it, thank you!

2022-10-12 07:33 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/bronze/books-bronze.py
> +# MAGIC create or replace Temporary view books_bronze_tmp as select * from books_raw_temp
i will modify this as well

2022-10-14 14:08 UTC, MarekTejcDS approved these changes
It looks good :)

2022-10-17 06:03 UTC, merged

2022-10-19 07:37 UTC, ondrejhavlicek reviewed
Really quite nice, just some minor things to potentially fix..

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years.py
> +)
you can use df.write.saveAsTable instead of views and SQL. Also, where will the data be stored using your code? You should store all data into lake.

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years-statistics.py
> +    )
This computation should have some comments explaining what it does and why.. I think I understand it, I recognize the IMDB formula, but others might not. There are also some choices like computing the prior stats per publisher and year - why? and the min_votes_required as avg. of number of ratings - why? Isn't average too high of a number?

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years-statistics.py
> +    .drop(f.col("How_many_ratings"))
Instead of the drops you can write a select and keep only the columns you need: this way you also kind of define an interface and it checks that the columns you need to be output to the table really exist.

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-ratings-for-statistics.py
> +m = min_votes_required[0].__getitem__("min_votes_required")
Instead of `__getitem__("min_votes_required")` you can write simply `["min_votes_required"]`, I think.

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-ratings-for-statistics.py
> +m = min_votes_required[0].__getitem__("min_votes_required")
But more importantly, can you write the code without doing collects? E.g. using window functions or aggregations and joins.. that approach could be faster thanks to the lazy evaluation and spark query optimization. Now each collect executes a separate spark job, which can be slow sometimes.

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years-statistics.py
> +    )
Using a different name of column will also help, instead of "Rating_for_statistics" e.g. "Rating_score", "Rating_bayesian_avg", "Rating_IMDB_score".. not sure :)

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors-by-year-and-publisher.py
> +def get_years(df):
Function description can be done using a so called docstring: https://peps.python.org/pep-0257/

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors-by-year-and-publisher.py
> +except ValueError:
You can omit the raising and catching of exceptions here, because the exception now just prints a message and you can do it simply by using an IF statement on line 49.. You can stop execution of notebook via dbutils.notebook.exit('some message') if you want

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors-by-year-and-publisher.py
> +        )
Luckily spark switches the where and select commands behind the scenes, but it would be better to directly write them in the correct order: first filter the rows, then select columns

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/average_book_rating_per_gender.py
> +# Databricks notebook source
the queries-for-statistics maybe should not be a subfolder of "gold"..

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors.py
> +display(df.limit(10))
These limit statements might not work as you expect if the data are large and get loaded into memory in multiple partitions, on multiple machines.. This can simple take top 10 from one of the machines but maybe not globally the top 10 rated authors. How could you solve this?

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/most-popular-10-books.py
> +    if 646 <= period and period <= 1:
In that case you should turn the number into a reasonably named constant that explains the meaning of the number

2022-10-19 07:37 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/silver/users-pii-silver.py
> +    .drop(f.col("lastName"))
Well, there was no requirement to concat the names into fullname, so as you wish, but beware that this potentially loses information: which part of the name is first, which middle..

2022-10-19 09:05 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors.py
> +display(df.limit(10))
I think we can do multiple limits on each partition and union between them afterwards! But i think that for now in this particular example there is no need because the table used for the limit(authors_ratings_for_statistics) , even if he has the first 1000 rows only,  it's ordered already.

2022-10-19 09:58 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years-statistics.py
> +df = year_publisher_ratings.groupBy("Year-Of-Publication", "Publisher").agg(
year_publisher_ratings = spark.table("authors_pub_years")

intermediar_df =(year_publisher_ratings
                     .groupBy("Year-Of-Publication", "Publisher")
                     .agg(f.avg("Number_of_ratings").cast("int").alias("min_votes_required"),
                          f.avg("Rating-Average").alias("Avg_note"),
                     )
                )

Tried to format it like this on my own and is not passing the linter, so i will live it as it is with black formatter

2022-10-19 12:18 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years-statistics.py
> +    )
This was the table created to help on the best-rated-10-authors-by-year-and-publisher notebook. From the exercise i understood that  we need to return the first 10 best rated by year and publisher so, what i understood by year and publisher was that maybe we have publisher "cris" and we want to see best rated  10 author on publisher "cris" in year 2000, but maybe, we want to see if the ratings of books for publisher "cris" increased by year 2001 in  rapport with the query with 2000 so that's why i chose to do it like that.

2022-10-19 13:09 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors-by-year-and-publisher.py
> +except ValueError:
I don't understand exactly because the idea is that the Publisher must be valid and from the list of publishers, and that's why i'm  raising an error.

2022-10-19 13:44 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/gold/authors-ratings-for-statistics.py
> +m = min_votes_required[0].__getitem__("min_votes_required")
The __getitem__ modified with only ["column_name] i did it but i dont't think i know how exactly to do this without collect here, because i tried in many ways and i did not get what i wanted. I found a function called first()  "m = df.select("min-votes-required").first()[0]" like that, but i don't know if this is the best practice. So if you can help me i would be grateful.

2022-10-19 15:43 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors.py
> +display(df.limit(10))
Not sure how you would do a limit on each partition.. The ordering can be distributed so I think the limit might not necessarily take the globally-highest 10 values, but e.g. 10 highest from some single partition..

2022-10-19 15:46 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years-statistics.py
> +df = year_publisher_ratings.groupBy("Year-Of-Publication", "Publisher").agg(
Then think how to format it so that it passes... hint:
intermediar_df = (
  year_publisher_ratings

2022-10-20 06:43 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/most-popular-10-books.py
> +    if 646 <= period and period <= 1:
`max_num_of_period ` is better. But the condition still doesnt read like a sentence a human not familiar with the code can understand. It may be best to even rewrite it a bit. What if someone runs the code next year, will it be still true that 646 is the maximum possible shift of year? How about

`OLDEST_BOOK_PUBLISHED_YEAR = 1376` 
(upper case is usually used for such hardcoded constants) 
and then 
`if year_from < OLDEST_BOOK_PUBLISHED_YEAR or year_from > current_year:` 
(now this condition can be read like a sentence. transforming the variable `period` to `year_from` makes the code more readable I think..)

2022-10-20 06:45 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/workflow_config.json
> +                "existing_cluster_id": "1011-112954-bj28ofn5",
Excellent, even with the spark_conf settings!

2022-10-20 06:46 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/workflow_config.json
> +                        "task_key": "best_rated_10_authors"
good!

2022-10-20 06:46 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/cleaning_checkpoints.py
> +dbutils.fs.rm(
great!

2022-10-20 06:47 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years-statistics.py
> +df = year_publisher_ratings.groupBy("Year-Of-Publication", "Publisher").agg(
I also think using dashes is less safe than underscores in column names. Some other tools that might want to work with the tables could understand dashes as a minus operator..

2022-10-20 06:48 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years.py
> +        f.avg("Book-Rating").alias("Rating-Average"),
I think using dashes is less safe than underscores in column names. Some other tools that might want to work with the tables could understand dashes as a minus operator..

2022-10-20 06:49 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years.py
> +)
Better, but where does the data get stored physically? Are they going to be in the lake (good) or somewhere in DBFS (bad)?

2022-10-20 06:51 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years-statistics.py
> +    )
Well, you should explain this in the code (by using comments and descriptive names of variables and columns), not here :)

2022-10-20 06:53 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-pub-years-statistics.py
> +    .drop(f.col("How_many_ratings"))
You didnt change this, did you? If not, you should reply here why not, before resolving the comment..

2022-10-20 06:56 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/authors-ratings-for-statistics.py
> +m = min_votes_required[0].__getitem__("min_votes_required")
Pretty much the same way you did it in `authors-pub-years-statistics.py` : you create a dataframe with just one row and two columns with the statistics and you join this back to the original dataframe. Or instead of aggregation and join you can use a window function.

2022-10-20 14:50 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/most-popular-10-books.py
> +    if 646 <= period and period <= 1:
Ok ,why not :) But, can this condition ever be true?

2022-10-21 08:01 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/most-popular-10-books.py
> +    if 646 <= period and period <= 1:
My bad, it needs to be or

2022-10-21 09:09 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors-by-year-and-publisher.py
> +        )
ok!

2022-10-21 09:10 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/most-popular-10-books.py
> +    if 646 <= period and period <= 1:
ok!

2022-10-24 11:32 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors.py
> +display(df.limit(10))
Actually, the first possible approach is simply read-order-limit. Doing the coalesce is not completely safe.

2022-10-24 11:41 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors.py
> +display(df.limit(10))
so as i did first ?

2022-10-24 12:15 UTC, ondrejhavlicek commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors.py
> +display(df.limit(10))
You did order before writing, not after reading, right?

2022-10-25 07:21 UTC, VlsDanielaGb commented on src/daniela-gabriela-vlasceanu/gold/queries-for-statistics/best-rated-10-authors.py
> +display(df.limit(10))
I tried to do a intermediate table that could be used for more queryes, so if i want to take worst rated authors to take them from the previous orderd and saved table