Andrei tugmeanu books
DataSentics/dsacademy-books pull request #9
Opened 2022-10-12 10:10 UTC by andrei-tugmeanu

Finished the project

2022-10-12 13:52 UTC, MarekTejcDS requested changes
I think that `writeStream` can have its own function, because it's mostly same code which differentiate only in paths and table name - in similar way as `Autoloader`

Please be aware, that until you cancel/destroy streams they are kept alive on cluster - for our example can be very handy if you check if there is any running stream in the end of procedures and stop it.

2022-10-12 13:52 UTC, MarekTejcDS commented on src/Silver_layer/silver_books.py
> +        when(col("Year_Of_Publication") == "0", "Unknown").otherwise(
Be aware that comparison is mostly NOT case sensitive, so it's good idea, to have `Unknown` or `unknown` only, not combination.

2022-10-12 13:52 UTC, MarekTejcDS commented on src/Set_paths/silver_paths.py
> +
I think that short comment can be quite helpful about sections of theses variables.

Also part of these paths are mostly same, it can be stored as another variable (?)

2022-10-12 13:52 UTC, MarekTejcDS commented on src/Set_paths/bronze_paths.py
> +
I think that short comment can be quite helpful about sections of theses variables.

Also part of these paths are mostly same, it can be stored as another variable (?)

2022-10-12 13:52 UTC, MarekTejcDS commented on src/Gold_layer/Task_3.py
> +result_df = aux_df.sort(col("Rating_score").desc(), col("Nr_of_ratings").desc()).limit(10)
You are not showing or storing anything here - please add show, display or create table/view

2022-10-12 13:52 UTC, MarekTejcDS commented on src/Gold_layer/Task_2.py
> +)
You are not showing or storing anything here - please add show, display or create table/view

2022-10-12 13:52 UTC, MarekTejcDS commented on src/Gold_layer/Task_4.py
> +)
You are not showing or storing anything here - please add show, display or create table/view

2022-10-12 13:52 UTC, MarekTejcDS commented on src/Gold_layer/Task_5.py
> +)
You are not showing or storing anything here - please add show, display or create table/view

2022-10-12 13:52 UTC, MarekTejcDS commented on src/Gold_layer/Task_1.py
> +main()
Shouldn't be there more displays (?)

2022-10-12 13:52 UTC, MarekTejcDS commented on src/Gold_layer/Task_1.py
> +    return var_pick
It can be bit more descriptive

2022-10-14 13:55 UTC, MarekTejcDS approved these changes
Seems good to me :) 

Please, `resolve conversations` that I commented to you

2022-10-17 05:58 UTC, merged

2022-10-24 15:01 UTC, ondrejhavlicek reviewed
There is still some work to do to improve this solution!

2022-10-24 15:01 UTC, ondrejhavlicek commented on src/Gold_layer/Task_4.py
> +    .filter("Country != 'n/a'")
If the country can have this kind of value, you should clean it in the silver _cleansed layer and here you would just write f.col(..).isNotNull()